src/ShopBundle/Entity/Item.php
<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Item
 *
 * @ORM\Table(name="item")
 * @ORM\Entity()
 */
class Item
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="category", type="string", length=255)
     */
    private $category;

    /**
     * @var int
     *
     * @ORM\Column(name="quantity", type="integer")
     */
    private $quantity;

    /**
     * @var string
     *
     * @ORM\Column(name="price", type="decimal", precision=5, scale=2)
     */
    private $price;

    /**
     * @var string
     *
     * @ORM\Column(name="tax", type="decimal", precision=3, scale=2)
     */
    private $tax;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Item
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }


    /**
     * Set category
     *
     * @param string $category
     * @return Item
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * Get category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     * @return Item
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set price
     *
     * @param string $price
     * @return Item
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set tax
     *
     * @param string $tax
     * @return Item
     */
    public function setTax($tax)
    {
        $this->tax = $tax;
    }

    /**
     * Get tax
     *
     * @return string
     */
    public function getTax()
    {
        return $this->tax;
    }

    /**
     * Get price
     *
     * @return string
     */
    public function getGrossPrice()
    {
        return bcmul($this->getPrice(), $this->getTax(), 2);
    }
}

src/ShopBundle/Controller/ShopController.php
<?php

namespace ShopBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

class ShopController extends Controller
{
    /**
     * Lists all shop items.
     *
     * @Route("/", name="shop")
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        return [
            'items' => $em->getRepository('ShopBundle:Item')->findAll(),
            'cart' =>$this->get("shop.cart"),
        ];
    }
}

src/ShopBundle/Resources/views/Shop/index.html.twig
{% extends 'ShopBundle::base.html.twig' %}

{% block mainContainer -%}

    <div class="row">
        <div class="items-list col-xs-12 col-sm-6 col-md-8">
            <h2>Items list</h2>
            {% for item in items %}
                {% include 'ShopBundle:Shop:item.html.twig' %}
            {% endfor %}
        </div>
        <div class="cart-items-list col-xs-6 col-md-4">
            <div style="margin: 25px 0">
            <h2 style="display: inline">Cart</h2>
            <a class="btn btn-default btn-danger pull-right" href="{{ path('cart_remove_all') }}">Remove all</a>
            </div>
            <div class="row">
                <h4>Standard vat:</h4>
                {% for itemInCart in cart.getItemsGroupedByVat.standard_vat %}
                    {% include 'ShopBundle:Shop:Cart/item.html.twig' %}
                {% endfor %}
            </div>
            <div class="row">
                <h4>Reduced vat:</h4>
                {% for itemInCart in cart.getItemsGroupedByVat.reduced_vat %}
                    {% include 'ShopBundle:Shop:Cart/item.html.twig' %}
                {% endfor %}
            </div>
            <div class="row summary">
                <h4>Summary: </h4>
                <p>total price for standard vat items: {{ cart.totalStandardVatItemsPrice }} zł</p>
                <p>total price for reduced vat items: {{ cart.totalReducedVatItemsPrice }} zł</p>
                <h4>total: <u>{{ cart.totalPrice }} zł</u></h4>
            </div>
        </div>
    </div>
{% endblock %}

src/ShopBundle/Resources/views/Shop/item.html.twig
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="http://lorempixel.com/200/150/{{ item.category }}/{{ loop.index }}" alt="">

        <div class="caption">
            <h3><u>{{ item.name |capitalize }}</u></h3>
            <h4>category: {{ item.category  }}</h4>
            <p>gross: {{ item.grossPrice }} zł ({{ (item.tax - 1) *100 }} % vat) </p>
            in stock: <p class="pull-right">{{ item.quantity }}</p>
        </div>

        {% include 'ShopBundle:Shop:Cart/Form/addToCart.html.twig' %}
    </div>
</div>